### ISSUE TITLE
The quantity value for NTP Server on PATCH payload

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Protocol-Validator#26]
Hi,
For the three teat cases about NTP Server below:
1. REQ_PATCH_ARRAY_ELEMENT_REMOVE: "Within a PATCH request, the service shall accept null to remove an element."
2. REQ_PATCH_ARRAY_ELEMENT_UNCHANGED: "Within a PATCH request, the service shall accept an empty object {} to leave an element unchanged"
3. REQ_PATCH_ARRAY_TRUNCATE: "A PATCH request with fewer elements than in the current array shall remove the remaining elements of the array."

Due to the BMC default value only two NTP servers in our design, Redfish-Protocol-Validator tool will PATCH three NTP servers on the payload. Is there any way to not limit the need for three NTP servers on test tool?
![NetworkProtocol Maximum](https://user-images.githubusercontent.com/85208691/128471193-9b5b5482-b813-4096-b96f-8d66eecc0224.JPG)

**Comment by mraineri** [comment]
Since the point of these tests is to verify array behavior in a manner that won't impact connectivity of the system, we picked NTPServers as a fairly safe property to perform array testing that is likely to be widely supported. That said, we also assumed 3 is a fairly reasonable assumption as the smallest this array might be in an implementation, but from what you've shown us this assumption is wrong. We'll need to modify the test in the tool.

**Comment by mraineri** [comment]
@FelixD999 would you be able to test the branch Array-Test-Fixes to see if that addresses the issue for you? I don't have a system available that limits NTPServers to 2 like you do.
