### ISSUE TITLE
Ongoing or upcoming plans to address pending work (# TODOs)

### ISSUE THREAD

**Issue by leoprovido** [DMTF/Redfish-Protocol-Validator#60]
Dear @mraineri ,

I am a user of the Redfish Protocol Validator testing tool for a device that supports the Redfish service in our local area network. I am writing to inquire if there are any ongoing or upcoming plans to address pending work (# TODOs) on the following programs:

https://github.com/DMTF/Redfish-Protocol-Validator/blob/master/redfish_protocol_validator/constants.py
https://github.com/DMTF/Redfish-Protocol-Validator/blob/master/redfish_protocol_validator/resources.py
https://github.com/DMTF/Redfish-Protocol-Validator/blob/master/redfish_protocol_validator/security_details.py
https://github.com/DMTF/Redfish-Protocol-Validator/blob/master/redfish_protocol_validator/service_details.py
https://github.com/DMTF/Redfish-Protocol-Validator/blob/master/redfish_protocol_validator/service_requests.py
https://github.com/DMTF/Redfish-Protocol-Validator/blob/master/redfish_protocol_validator/service_responses.py
https://github.com/DMTF/Redfish-Protocol-Validator/blob/master/redfish_protocol_validator/system_under_test.py

Additionally, I would appreciate it if you could point me towards the "notes on testing by Mike R." that are on this repository.

Thank you for your assistance.

Sincerely,
Leo

**Comment by mraineri** [comment]
This certainly fell off our radars. A quick look at the TODOs and it looks like many of them can simply be deleted. I'll go through and see if that's the case and make changes accordingly (or file new issues to track additional changes).

Unfortunately those notes were just things Bill wrote down from our conversations, and he's since retired so they likely aren't available anymore.
